network:
  version: 2
  ethernets:
    ens3:
      dhcp4: false
      addresses: ["192.168.200.2/24"]
      gateway4: 192.168.200.1
      nameservers:
        addresses: ["1.1.1.1", "8.8.8.8"]
    ens4: 
      dhcp4: false
      addresses: ["10.0.0.1/24"]

      
