#cloud-config
hostname: apache2
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH1qXm0g8aBKSRDP3YN+ZycRzKQgE1+dLk1o3gxtw7o6 ddorluc760@iesalmudeyne.es
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text


