- name: Actualizar el sistema y los paquetes
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600

- name: AÃ±adir las entradas de la red interna al fichero /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE RED INTERNA"
    block: |
      10.0.0.2 mariadb.biblioteca.org
      10.0.0.1 apache2.biblioteca.org
    owner: root
    group: root
    mode: '0644'
