- name: ensure mariadb is installed
  apt:
    pkg:
      - mariadb-server
      - python3-mysqldb
    state: latest
    update_cache: yes

- name: Crear base de datos
  community.mysql.mysql_db:
    name: "{{ biblioteca_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Crear usuario y otorgar privilegios
  community.mysql.mysql_user:
    name: "{{ biblioteca_db_user }}"
    password: "{{ biblioteca_db_password }}"
    host: "%"
    priv: "{{ biblioteca_db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock


- name: Configurar MariaDB para escuchar en todas las interfaces
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present
  notify: restart mariadb

- name: Descargar esquema SQL directamente desde GitHub en MariaDB
  get_url:
    url: "https://raw.githubusercontent.com/VidaInformatico/Sistema-de-biblioteca-basico-php-8-y-mysql/master/biblioteca.sql"
    dest: /tmp/biblioteca.sql

- name: Comprobar si la base de datos tiene tablas
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: "SELECT COUNT(*) AS total FROM information_schema.tables WHERE table_schema='{{ biblioteca_db_name }}';"
  register: db_table_count

- name: Importar esquema SQL en MariaDB
  community.mysql.mysql_db:
    name: "{{ biblioteca_db_name }}"
    state: import
    target: "/tmp/biblioteca.sql"
    login_user: "root"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
  when: db_table_count.query_result[0][0].total | int == 0
